services:

  # database:
  #   image: timescale/timescaledb:latest-pg16
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: traccar
  #     POSTGRES_USER: traccar
  #     POSTGRES_PASSWORD: traccar
  #     TIMESCALEDB_TELEMETRY: "off"
  #   volumes:
  #     - ./data/postgresql:/var/lib/postgresql/data

  traccar:
    build: .
    # image: traccar/traccar:latest
    restart: unless-stopped
    # depends_on:
    #   - database
    environment:
      CONFIG_USE_ENVIRONMENT_VARIABLES: "true"
      DATABASE_DRIVER: org.postgresql.Driver
      DATABASE_URL: jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?pgbouncer=true
      DATABASE_USER: postgres.xspkeynlexpiyjzzoyul
      DATABASE_PASSWORD: "0b9r!hUz2&IZ"
      # Enable OsmAnd protocol for HTTP-based testing
      OSMAND_PORT: "5055"
      # Enable GPS103 protocol for TCP testing (TK103 devices)
      GPS103_PORT: "5001"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8082/api/health" ]
      interval: 2m
      timeout: 5s
      start_period: 1h
      retries: 3
    ports:
      - "8082:8082"
      - "5000-5500:5000-5500"
    volumes:
      - ./data/logs:/opt/traccar/logs

  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
      AUTOHEAL_INTERVAL: 60
      AUTOHEAL_START_PERIOD: 3600
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
